---
- name: Obtener hostname de los servidores
  hosts: all
  gather_facts: yes  # Recopila información del sistema automáticamente
  tasks:
    - name: Mostrar el hostname recopilado por Ansible
      ansible.builtin.debug:
        msg: "El hostname de este servidor es: {{ ansible_hostname }}"