---
- name: Configurar mensaje de bienvenida
  hosts: all
  vars:
    apache_package: httpd
    apache_port: 80
    welcome_message: "¡Bienvenido al Webinar de Ansible!"
  tasks:
    - name: Asegurar que Apache esté instalado
      dnf:
        name: "{{ apache_package }}"
        state: present

    - name: Crear página web desde template
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: Asegurar que el servicio esté corriendo
      service:
        name: "{{ apache_package }}"
        state: started
        enabled: yes